spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reviewscope?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: reviewuser
    password: Rw2026_1320
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true